# Generated by Django 3.0.2 on 2020-03-05 03:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_name', models.CharField(default='', max_length=64, unique=True)),
                ('camera_def', models.CharField(default='', max_length=100)),
                ('camera_cost', models.IntegerField(default='0')),
                ('camera_image', models.ImageField(null=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('working_hour', models.CharField(max_length=200)),
                ('day_off', models.CharField(max_length=200)),
                ('phones', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ShortDefenitionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('defenition_image', models.ImageField(null=True, upload_to='short-def-images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='ShortDefenition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera_short_def', models.CharField(max_length=200)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Filter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_filter', models.CharField(choices=[('a', 'Hikvision'), ('b', 'HiWatch'), ('c', 'Ezviz')], max_length=1, verbose_name='Бренды')),
                ('camera_filter', models.CharField(choices=[('a', 'IP'), ('b', 'HD-TVI'), ('c', 'Аналог'), ('d', 'Уличная'), ('e', 'Купольная'), ('f', 'Офисная'), ('g', 'Встраиваемая'), ('h', 'Офисная')], max_length=1, verbose_name='Тип камеры')),
                ('frame_filter', models.CharField(choices=[('a', 'Стандартный корпус'), ('b', 'Купольная'), ('c', 'Цилиндрическая'), ('d', 'Компактная'), ('e', 'Мини-купольная'), ('f', 'Панорамная'), ('g', 'Поворотная')], max_length=1, verbose_name='Тип корпуса')),
                ('pos_filter', models.CharField(choices=[('a', 'Wi-Fi'), ('b', 'Встроенный микрофон'), ('c', 'Аудио вход для микрофона'), ('d', 'слот для SD карта'), ('e', 'ColorVu')], max_length=1, verbose_name='Возможности')),
                ('use_filter', models.CharField(choices=[('a', 'Внутреннее'), ('b', 'Уличное'), ('c', 'Антикоррозионное')], max_length=1, verbose_name='Исполнение')),
                ('zoom_filter', models.CharField(choices=[('a', 'Нет'), ('b', '4х'), ('c', '10х'), ('d', '20х'), ('e', '23х'), ('g', '25х'), ('g', '30х'), ('h', '32х'), ('i', '36х')], max_length=1, verbose_name='Оптическое увеличение')),
                ('sens_filter', models.CharField(choices=[('a', 'CMOS 1/1.7"'), ('b', 'CMOS 1/1.8"'), ('c', 'CMOS 1/1.9"'), ('d', 'CMOS 1/2.5"'), ('e', 'CMOS 1/2.7"'), ('f', 'CMOS 1/2.8"'), ('g', 'CMOS 1/3"'), ('h', 'CMOS 1/4"'), ('i', 'CMOS')], max_length=1, verbose_name='Оптический сенсор')),
                ('mp_filter', models.CharField(choices=[('a', '1 Мп'), ('b', '1,3 Мп'), ('c', '2 Мп'), ('d', '3 Мп'), ('e', '4 Мп'), ('f', '5 Мп'), ('g', '6 Мп'), ('h', '8 Мп'), ('i', '12 Мп'), ('j', '16 Мп'), ('k', '18 Мп')], max_length=1, verbose_name='Кол-во мегапикселей')),
                ('ik_filter', models.CharField(choices=[('a', 'Нет'), ('b', 'До 3 м'), ('c', 'До 10 м'), ('d', 'До 15 м'), ('e', 'До 20 м'), ('f', 'До 30 м'), ('g', 'До 40 м'), ('h', 'До 50 м'), ('i', 'До 70 м'), ('j', 'До 80 м'), ('k', 'До 100 м'), ('l', 'До 110 м'), ('m', 'До 120 м'), ('n', 'До 150 м'), ('o', 'До 200 м'), ('p', 'До 500 м (лазер)'), ('r', 'До 800 м (лазер)'), ('s', 'До 1000 м (лазер)')], max_length=1, verbose_name='ИК-подсветка')),
                ('prot_filter', models.CharField(choices=[('a', 'Нет'), ('b', 'IP66'), ('c', 'IP67'), ('d', 'IP68'), ('e', 'NEMA4X C5-M')], max_length=1, verbose_name='Защита от пыли/влаги')),
                ('sup_filter', models.CharField(choices=[('a', '12VDC'), ('b', '24VAC'), ('c', 'PoE 802.3aF'), ('d', 'High-PoE 802.3at'), ('e', 'PoC (TVI)'), ('f', '36VDC')], max_length=1, verbose_name='Питание')),
                ('wdr_filter', models.CharField(choices=[('a', 'DWDR'), ('b', 'WDR 120дб'), ('c', 'WDR 140дб')], max_length=1, verbose_name='WDR')),
                ('var_filter', models.CharField(choices=[('a', 'Да')], max_length=1, verbose_name='Вариофокальный объектив')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.Camera')),
            ],
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=200)),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='camera.Camera')),
            ],
        ),
        migrations.AddField(
            model_name='camera',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='camera', to='camera.Category'),
        ),
    ]
