# Generated by Django 3.0.2 on 2020-03-06 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('camera', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessory_name', models.CharField(max_length=50)),
                ('accessory_description', models.CharField(max_length=150)),
                ('accessory_image', models.ImageField(null=True, upload_to='accessory-images/')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='camera.Camera')),
            ],
        ),
    ]
